# Generated by Django 4.2 on 2024-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.CharField(max_length=20, unique=True)),
                ("userPw", models.CharField(max_length=20)),
                ("userName", models.CharField(max_length=20)),
                ("userEmail", models.CharField(max_length=50)),
            ],
        ),
    ]
